# Generated by Django 5.2 on 2025-05-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitor',
            name='telefone',
            field=models.CharField(default=1, max_length=15, verbose_name='Telefone do leitor'),
            preserve_default=False,
        ),
    ]
