# Generated by Django 5.2.1 on 2025-05-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_leitor_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='data_plub',
            new_name='data_pub',
        ),
    ]
