# Generated by Django 5.2.1 on 2025-05-26 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reserva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_pub',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.editora'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='leitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.leitor'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.livro'),
        ),
    ]
